/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:ecb0f219-1d7d-4536-aaa9-80e8929271c6",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_Dr0c2m4X9",
    "aws_user_pools_web_client_id": "5nbb0edem9k8hpr27ne13pj8vi",
    "oauth": {},
    "aws_user_files_s3_bucket": "superbook36a752dd1f674f80bf9e084fe6cf30d282004-dev",
    "aws_user_files_s3_bucket_region": "eu-west-2",
    "aws_appsync_graphqlEndpoint": "https://xjigtvpryza6jidpaqd5ghfnci.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-gwmwwbwi5vcjxoztzbzxlpu5yu",
    "aws_content_delivery_bucket": "superbook-20200812073718-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-2",
    "aws_content_delivery_url": "https://d3808ja3dwvalh.cloudfront.net"
};


export default awsmobile;
